Repository fabianhinz/learnToCode, pull requests merged in 2020-09, with the labels that each got.

#22 improve logging and fix infinity loop while validating nodes
  Plattform/gatsby-node.js
  Plattform/node-apis/create-markdown-pages.js
  Plattform/node-apis/node-apis-constants.js
  Plattform/node-apis/validate-markdown-fields.js
Labels: bug, enhancement

#23 update platform readme with debugging information
  Plattform/README.md
Labels: enhancement

#20 Improvement/save lectures
  Plattform/package-lock.json
  Plattform/package.json
  Plattform/src/components/Catalog/CatalogLecture.tsx
  Plattform/src/components/Catalog/CatalogRoot.tsx
  Plattform/src/components/Introduction/Introduction.tsx
  Plattform/src/components/Layout/RootLayout.tsx
  Plattform/src/components/Lecture/LectureRating.tsx
  Plattform/src/components/Provider/FirebaseProvider.tsx
  Plattform/src/components/Provider/LectureProvider.tsx
  Plattform/src/components/Provider/ProgressProvider.tsx
  Plattform/src/components/Provider/RatingProvider.tsx
  Plattform/src/components/Stackblitz/Stackblitz.tsx
  Plattform/src/components/Stackblitz/StackblitzContainer.tsx
  Plattform/src/components/User/User.tsx
  Plattform/src/components/User/UserAvatar.tsx
  Plattform/src/components/User/UserLectures.tsx
  Plattform/src/model/firebase.ts
  Plattform/src/model/model.ts
Labels: enhancement

#30 improve github and stackblitz integration. Hide platform on mobile
  Katalog/Front-End-Webentwicklung/React/Props/props.md
  Katalog/Front-End-Webentwicklung/React/State/state.md
  Plattform/gatsby-config.js
  Plattform/node-apis/create-markdown-pages.js
  Plattform/src/components/Catalog/CatalogErrorBoundary.tsx
  Plattform/src/components/Catalog/CatalogLecture.tsx
  Plattform/src/components/Layout/layout.css
  Plattform/src/components/Lecture/LectureSpeedDial.tsx
  Plattform/src/components/Main.tsx
  Plattform/src/components/Stackblitz/Stackblitz.tsx
  Plattform/src/components/Stackblitz/StackblitzContainer.tsx
  Plattform/src/model/model.ts
  Plattform/src/util/constants.ts
  Plattform/src/util/github-service.ts
  Plattform/static/viewportTooSmall.png
Labels: feature, platform

#33 Feature/lecture templates
  Katalog/Thema/Technologie/Lektion/lektion.md.tmpl
  Katalog/Thema/technologie.md.tmpl
  Katalog/thema.md.tmpl
Labels: feature, lerninhalt
